import Head from 'next/head'
import Image from 'next/image'
import MainSlider from '../components/mainSlider/MainSlider'
import styles from '../styles/Home.module.css'
import About from '../components/about/About'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <section>
         <MainSlider />
       </section>
        <section className="mt-10">
           
            <About />
            
        </section>
       
     
    </div>
  )
}
